# Generated by Django 5.2.4 on 2025-07-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('artist', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
