# Generated by Django 5.2.4 on 2025-07-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_song_audio_file_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(),
        ),
    ]
